config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create , :destroy]
  devise_for :users
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create,:index,:destroy]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name:'User'
end

app/models/stock.rb
require 'finnhub_ruby'

class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    stock = find_by(ticker: ticker_symbol)

    unless stock
      FinnhubRuby.configure do |config|
        config.api_key['api_key'] = 'chjhig9r01qh5480h190chjhig9r01qh5480h19g' # Replace with your actual API key
      end

      finnhub_client = FinnhubRuby::DefaultApi.new
      quote = finnhub_client.quote(ticker_symbol)
      company_profile = finnhub_client.company_profile2(symbol: ticker_symbol)

      stock = new(
        ticker: ticker_symbol,
        name: company_profile.name,
        last_price: quote.c
      )
    end

    stock
  end
  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



         def stock_already_tracked?(ticker_symbol)
          stock = Stock.check_db(ticker_symbol)
          return false unless stock
          stocks.where(id: stock.id).exists?
         end

         def  under_stock_limit?
          stocks.count < 10
         end
         def can_track_stock?(ticker_symbol)
           under_stock_limit?  && !stock_already_tracked?(ticker_symbol)
         end

         def self.search(param)
          param.strip!
          to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
          return nil unless to_send_back
          to_send_back
        end
        def self.first_name_matches(param)
          matches('first_name',param)
        end
        def self.last_name_matches(param)
          matches('last_name',param)
        end
        def self.email_matches(param)
          matches('email',param)
        end
        def self.matches(field_name, param)
         where("#{field_name} like ?", "%#{param}%")
        end
        def except_current_user(users)
          users.reject{|user|user.id == self.id}
        end
        def not_friends_with(id_of_friend)
           !self.friends.where(id: id_of_friend).exists?
        end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def index
    friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: friend.id)
    if current_user.save
      flash[:notice] = "Following friend"
    else
      flash[:alert] = "There was something wrong with the tracking request"
    end
    redirect_to my_friends_path

  end
  def create

  end

  def destroy
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy
    flash[:notice] = "Stopped following"
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    @stock = Stock.new_lookup(params[:stock])
    if @stock.present? && @stock.last_price.present? && @stock.name.present? && @stock.ticker.present?
      render 'users/my_portfolio'
    else
      flash.now[:alert] = 'Stock not found or incomplete data'
      render 'users/my_portfolio'
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} was successfully added to your portfolio."
    redirect_to my_portfolio_path
  end
  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "Stock #{stock.name} was successfully removed from your portfolio"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_stocks = current_user.stocks
  end
  def my_friends
    @friends = current_user.friends
  end
  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end

  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
    end
    render partial: 'users/friend_result'
  end


end

app/controllers/welcome_controller.rb
require 'httparty'

class WelcomeController < ApplicationController
  def index
    @stock_news = fetch_stock_news
  end

  private

  def fetch_stock_news
    api_key = '4d940f1e6a4748c5b8fc4e95d2038da3'
    url = "https://newsapi.org/v2/everything?q=stock&apiKey=#{api_key}"

    response = HTTParty.get(url)
    news_data = JSON.parse(response.body)

    news_data['articles'].select { |article| article['urlToImage'].present? }
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_list.html.erb
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Email</th>
        <th>first Name</th>
        <th>last name</th>
      </tr>
    </thead>
    <tbody>
      <% @friends.each do |friends| %>
        <tr>
          <td><%= friends.email %></td>
          <td><%= friends.first_name %></td>
          <td><%= friends.last_name %></td>
          <td>  <strong>Profile: </strong> <%= link_to 'View Profile', user_path(friends), class: "btn btn-sm btn-success" %></td>
          <td> <%= link_to 'Stop following', friendship_path(friends), method: :delete, data: { turbo_method: :delete }, class: 'btn btn-sm btn-warning' %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FiTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary" id="main-nav">
  <div class="container-fluid">
    <%= link_to 'FinanaceTracker',root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navba<li class="nav-item">
          <a class="nav-link disabled">Link</a>
        </li>rSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       <li class="nav-item">
         <%= link_to 'My Portfolio', my_portfolio_path, class: "nav-link active" %>
       </li>

        <li class="nav-item">
  <%= link_to 'My Friends', my_friends_path, class: "nav-link active" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Profile
          </a>
          <ul class="dropdown-menu" style ="background-color:rgb(38, 57, 77);">
            <%= link_to 'Edit Profile', edit_user_registration_path, class: 'dropdown-item'%>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item user-name">
            <% if current_user %>
                   <%= current_user.first_name %>  <%= current_user.last_name%> <%= link_to 'logout', destroy_user_session_path, method: :delete, data: { turbo_method: :delete } ,class: "btn btn-outline-danger"  %>
                 <% end %>
        </li>
      </ul>
      <form class="d-flex" role="search">

            </div>
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
     <p class="notice"><%= notice %></p>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>  bg-danger">
    <%= value %>
  </div>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/stocks/_list.html.erb
  <div id="tracked-stocks-section">
    <h3 class= "tracked-stocks">Tracked Stocks</h3>
    <table class="table">
      <thead>
        <tr>
          <th>Stock Name</th>
          <th>Ticker</th>
          <th>Last Price</th>
          <th>Action </th>
        </tr>
      </thead>
      <tbody>
        <% @tracked_stocks.each do |tracked_stock| %>
          <tr>
            <td><%= tracked_stock.name %></td>
            <td><%= tracked_stock.ticker %></td>
            <td><%= tracked_stock.last_price %></td>
             <td> <%= link_to 'Remove', user_stock_path(tracked_stock), method: :delete, data: { turbo_method: :delete }, class: 'btn btn-sm btn-warning' %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

app/views/users/_friend_result.html.erb
<% if @friends %>
  <div class="card card-header results-block">
    <% @friends.each do |friend| %>
      <strong>Email: </strong> <%= friend.first_name %><%= friend.last_name %>
      <strong>Name: </strong> <%= friend.email %>
      <strong>Profile: </strong> <%= link_to 'View Profile', user_path(friend), class: "btn btn-sm btn-success" %>
      <% if current_user.not_friends_with(friend.id) %>
        <%= link_to 'Follow friend', friendships_path(friend: friend.id), class: "btn btn-sm btn-success", method: :post, data: { turbo_method: :post } %>
      <% else %>
        You are already friends
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/users/_result.html.erb
<table class="table table-bordered stock-details-table">
  <thead>
    <tr>
      <th>Symbol</th>
      <th>Company Name</th>
      <th>Last Price</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @stock.ticker %></td>
      <td><%= @stock.name %></td>
      <td><%= @stock.last_price %> $</td>
      <td>
        <% if current_user.can_track_stock?(@stock.ticker) %>
          <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker), class: "btn btn-sm btn-success", method: :post, data: { turbo_method: :post } %>
        <% else %>
          <% if !current_user.under_stock_limit? %>
            <span class=" custum_color ">10 stocks limit exeeded</span>
          <% end %>
          <% if current_user.stock_already_tracked?(@stock.ticker) %>
            <span class=" custum_color ">You are already tracking this stock</span>
          <% end %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

app/views/users/my_friends.html.erb
<h2>Friends</h2>
<div class='search-area'>
  <h3>Search Friends</h3>
  <%= form_tag search_friend_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: "Name or email", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3">
        <%= submit_tag "Search", class: "btn btn-success btn-lg" %>
      </div>
    </div>
  <% end %>
</div>
<% if @friends.present? && !@friends.empty? %>
  <%= render 'friends/list' %>
<% end %>

app/views/users/my_portfolio.html.erb
<div class = "container">
<h1 class = "card-heading">My Portfolio</h1>

<div class='search-area'>
  <h3 style="text-shadow: 1px 1px; margin-bottom:12px; padding-left:5px;">Search Stocks</h3>
  <%= form_tag search_stock_path, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding portfolio-search">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3">
        <%= submit_tag "Search", class: "btn btn-success btn-lg" %>
      </div>
    </div>
  <% end %>
</div>

<% if @stock.present? %>
<%= render 'users/result'  %>
<% end %>
<% if @tracked_stocks.present? %>
<%= render 'stocks/list'  %>
<% end %>
</div>

app/views/users/show.html.erb
<h2>User Details</h2>


<div class="card card-header results-block">
  <table class="col-md-12">
    <tbody>
      <tr>
        <td><strong>Name: </strong> <%= @user.first_name %></td>
        <td><strong>Email: </strong> <%= @user.email %></td>
        <td>
          <% if current_user.not_friends_with(@user.id) %>
            <%= link_to 'Follow friend?', friendships_path(friend: @user),
                          class: "btn btn-sm btn-success", method: :post %>
          <% else %>
            <span class="badge badge-secondary">
              You are friends
            </span>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list'%>
<% else %>
  <p class='lead'>This user is not tracking any stocks</p>
<% end %>

app/views/welcome/index.html.erb
<div class="container-fluid">
 <h1 class="card-heading">
  <span class="word">Stock<span class="superscript">s</span> </span>
  <span class="word">News</span>
</h1>
  <div class="row cards">
    <% @stock_news.each do |article| %>
      <div class="col-md-4">
        <div class="card mb-4">
          <img src="<%= article['urlToImage'] %>" alt="Article Image" class="card-img card-img-top">
          <div class="card-body">
            <h5 class="card-title"><%= article['title'] %></h5>
            <p class="card-text"><%= article['description'] %></p>
            <a href="<%= article['url'] %>" class="btn btn-primary">Read More</a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>